/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxiRouteImport } from './routes/taxi'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PlansPricingRouteImport } from './routes/plans-pricing'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CabRouteImport } from './routes/cab'
import { Route as BusRouteImport } from './routes/bus'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BikePoolingRouteImport } from './routes/bike-pooling'
import { Route as BikeRouteImport } from './routes/bike'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusSeatsRouteImport } from './routes/bus.seats'
import { Route as BusResultsRouteImport } from './routes/bus.results'
import { Route as BusLoginRouteImport } from './routes/bus.login'
import { Route as BusConfirmationRouteImport } from './routes/bus.confirmation'
import { Route as BusCheckoutRouteImport } from './routes/bus.checkout'
import { Route as BusAccountRouteImport } from './routes/bus.account'

const TaxiRoute = TaxiRouteImport.update({
  id: '/taxi',
  path: '/taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPricingRoute = PlansPricingRouteImport.update({
  id: '/plans-pricing',
  path: '/plans-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CabRoute = CabRouteImport.update({
  id: '/cab',
  path: '/cab',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BikePoolingRoute = BikePoolingRouteImport.update({
  id: '/bike-pooling',
  path: '/bike-pooling',
  getParentRoute: () => rootRouteImport,
} as any)
const BikeRoute = BikeRouteImport.update({
  id: '/bike',
  path: '/bike',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusSeatsRoute = BusSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => BusRoute,
} as any)
const BusResultsRoute = BusResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => BusRoute,
} as any)
const BusLoginRoute = BusLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BusRoute,
} as any)
const BusConfirmationRoute = BusConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => BusRoute,
} as any)
const BusCheckoutRoute = BusCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BusRoute,
} as any)
const BusAccountRoute = BusAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => BusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto': typeof AutoRoute
  '/bike': typeof BikeRoute
  '/bike-pooling': typeof BikePoolingRoute
  '/blog': typeof BlogRoute
  '/bus': typeof BusRouteWithChildren
  '/cab': typeof CabRoute
  '/contact': typeof ContactRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/plans-pricing': typeof PlansPricingRoute
  '/services': typeof ServicesRoute
  '/taxi': typeof TaxiRoute
  '/bus/account': typeof BusAccountRoute
  '/bus/checkout': typeof BusCheckoutRoute
  '/bus/confirmation': typeof BusConfirmationRoute
  '/bus/login': typeof BusLoginRoute
  '/bus/results': typeof BusResultsRoute
  '/bus/seats': typeof BusSeatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto': typeof AutoRoute
  '/bike': typeof BikeRoute
  '/bike-pooling': typeof BikePoolingRoute
  '/blog': typeof BlogRoute
  '/bus': typeof BusRouteWithChildren
  '/cab': typeof CabRoute
  '/contact': typeof ContactRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/plans-pricing': typeof PlansPricingRoute
  '/services': typeof ServicesRoute
  '/taxi': typeof TaxiRoute
  '/bus/account': typeof BusAccountRoute
  '/bus/checkout': typeof BusCheckoutRoute
  '/bus/confirmation': typeof BusConfirmationRoute
  '/bus/login': typeof BusLoginRoute
  '/bus/results': typeof BusResultsRoute
  '/bus/seats': typeof BusSeatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto': typeof AutoRoute
  '/bike': typeof BikeRoute
  '/bike-pooling': typeof BikePoolingRoute
  '/blog': typeof BlogRoute
  '/bus': typeof BusRouteWithChildren
  '/cab': typeof CabRoute
  '/contact': typeof ContactRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/plans-pricing': typeof PlansPricingRoute
  '/services': typeof ServicesRoute
  '/taxi': typeof TaxiRoute
  '/bus/account': typeof BusAccountRoute
  '/bus/checkout': typeof BusCheckoutRoute
  '/bus/confirmation': typeof BusConfirmationRoute
  '/bus/login': typeof BusLoginRoute
  '/bus/results': typeof BusResultsRoute
  '/bus/seats': typeof BusSeatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auto'
    | '/bike'
    | '/bike-pooling'
    | '/blog'
    | '/bus'
    | '/cab'
    | '/contact'
    | '/flights'
    | '/hotels'
    | '/plans-pricing'
    | '/services'
    | '/taxi'
    | '/bus/account'
    | '/bus/checkout'
    | '/bus/confirmation'
    | '/bus/login'
    | '/bus/results'
    | '/bus/seats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auto'
    | '/bike'
    | '/bike-pooling'
    | '/blog'
    | '/bus'
    | '/cab'
    | '/contact'
    | '/flights'
    | '/hotels'
    | '/plans-pricing'
    | '/services'
    | '/taxi'
    | '/bus/account'
    | '/bus/checkout'
    | '/bus/confirmation'
    | '/bus/login'
    | '/bus/results'
    | '/bus/seats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auto'
    | '/bike'
    | '/bike-pooling'
    | '/blog'
    | '/bus'
    | '/cab'
    | '/contact'
    | '/flights'
    | '/hotels'
    | '/plans-pricing'
    | '/services'
    | '/taxi'
    | '/bus/account'
    | '/bus/checkout'
    | '/bus/confirmation'
    | '/bus/login'
    | '/bus/results'
    | '/bus/seats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutoRoute: typeof AutoRoute
  BikeRoute: typeof BikeRoute
  BikePoolingRoute: typeof BikePoolingRoute
  BlogRoute: typeof BlogRoute
  BusRoute: typeof BusRouteWithChildren
  CabRoute: typeof CabRoute
  ContactRoute: typeof ContactRoute
  FlightsRoute: typeof FlightsRoute
  HotelsRoute: typeof HotelsRoute
  PlansPricingRoute: typeof PlansPricingRoute
  ServicesRoute: typeof ServicesRoute
  TaxiRoute: typeof TaxiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taxi': {
      id: '/taxi'
      path: '/taxi'
      fullPath: '/taxi'
      preLoaderRoute: typeof TaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans-pricing': {
      id: '/plans-pricing'
      path: '/plans-pricing'
      fullPath: '/plans-pricing'
      preLoaderRoute: typeof PlansPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cab': {
      id: '/cab'
      path: '/cab'
      fullPath: '/cab'
      preLoaderRoute: typeof CabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bike-pooling': {
      id: '/bike-pooling'
      path: '/bike-pooling'
      fullPath: '/bike-pooling'
      preLoaderRoute: typeof BikePoolingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bike': {
      id: '/bike'
      path: '/bike'
      fullPath: '/bike'
      preLoaderRoute: typeof BikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus/seats': {
      id: '/bus/seats'
      path: '/seats'
      fullPath: '/bus/seats'
      preLoaderRoute: typeof BusSeatsRouteImport
      parentRoute: typeof BusRoute
    }
    '/bus/results': {
      id: '/bus/results'
      path: '/results'
      fullPath: '/bus/results'
      preLoaderRoute: typeof BusResultsRouteImport
      parentRoute: typeof BusRoute
    }
    '/bus/login': {
      id: '/bus/login'
      path: '/login'
      fullPath: '/bus/login'
      preLoaderRoute: typeof BusLoginRouteImport
      parentRoute: typeof BusRoute
    }
    '/bus/confirmation': {
      id: '/bus/confirmation'
      path: '/confirmation'
      fullPath: '/bus/confirmation'
      preLoaderRoute: typeof BusConfirmationRouteImport
      parentRoute: typeof BusRoute
    }
    '/bus/checkout': {
      id: '/bus/checkout'
      path: '/checkout'
      fullPath: '/bus/checkout'
      preLoaderRoute: typeof BusCheckoutRouteImport
      parentRoute: typeof BusRoute
    }
    '/bus/account': {
      id: '/bus/account'
      path: '/account'
      fullPath: '/bus/account'
      preLoaderRoute: typeof BusAccountRouteImport
      parentRoute: typeof BusRoute
    }
  }
}

interface BusRouteChildren {
  BusAccountRoute: typeof BusAccountRoute
  BusCheckoutRoute: typeof BusCheckoutRoute
  BusConfirmationRoute: typeof BusConfirmationRoute
  BusLoginRoute: typeof BusLoginRoute
  BusResultsRoute: typeof BusResultsRoute
  BusSeatsRoute: typeof BusSeatsRoute
}

const BusRouteChildren: BusRouteChildren = {
  BusAccountRoute: BusAccountRoute,
  BusCheckoutRoute: BusCheckoutRoute,
  BusConfirmationRoute: BusConfirmationRoute,
  BusLoginRoute: BusLoginRoute,
  BusResultsRoute: BusResultsRoute,
  BusSeatsRoute: BusSeatsRoute,
}

const BusRouteWithChildren = BusRoute._addFileChildren(BusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutoRoute: AutoRoute,
  BikeRoute: BikeRoute,
  BikePoolingRoute: BikePoolingRoute,
  BlogRoute: BlogRoute,
  BusRoute: BusRouteWithChildren,
  CabRoute: CabRoute,
  ContactRoute: ContactRoute,
  FlightsRoute: FlightsRoute,
  HotelsRoute: HotelsRoute,
  PlansPricingRoute: PlansPricingRoute,
  ServicesRoute: ServicesRoute,
  TaxiRoute: TaxiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
